AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: mecab

Parameters:
  Repository:
    Type: String
  FunctionName:
    Type: String

Resources:

  # Lambda Function
  MeCabFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${FunctionName}
      PackageType: Image
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:latest
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          LOG_LEVEL: INFO